[package]
name = "nbody"
version = "0.1.0"
authors = ["unexge <unexge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
rgx = "0.5.0"
winit = "0.20.0-alpha5"